from .base_attributes import (
    BooleanAttribute,
    ComposedAttribute,
    ComposePolicy,
    SimpleAttribute,
)

style_composer = ComposePolicy(
    lambda values: ";".join(values) + (";" if values else ""),
    lambda values: [v.strip() for v in values.split(";") if v.strip()],
    lambda k, v: f"{k}:{v}",
)

whitespace_composer = ComposePolicy(
    lambda values: " ".join(values),
    lambda values: values.split(),
)


id = SimpleAttribute("id")
class_ = ComposedAttribute("class", compose_policy=whitespace_composer)
style = ComposedAttribute("style", compose_policy=style_composer)

classes = class_  # alias for class_

accept = SimpleAttribute("accept")
accept_charset = SimpleAttribute("accept-charset")
accesskey = SimpleAttribute("accesskey")
action = SimpleAttribute("action")
align = SimpleAttribute("align")
allow = SimpleAttribute("allow")
alt = SimpleAttribute("alt")
as_ = SimpleAttribute("as")
async_ = BooleanAttribute("async")
autocapitalize = SimpleAttribute("autocapitalize")
autocomplete = SimpleAttribute("autocomplete")
autoplay = BooleanAttribute("autoplay")
capture = BooleanAttribute("capture")
charset = SimpleAttribute("charset")
checked = BooleanAttribute("checked")
cite = SimpleAttribute("cite")
colorspace = SimpleAttribute("colorspace")
cols = SimpleAttribute("cols")
colspan = SimpleAttribute("colspan")
content = SimpleAttribute("content")
contenteditable = BooleanAttribute("contenteditable")
controls = BooleanAttribute("controls")
coords = SimpleAttribute("coords")
crossorigin = SimpleAttribute("crossorigin")
data = SimpleAttribute("data")
datetime = SimpleAttribute("datetime")
decoding = SimpleAttribute("decoding")
default = BooleanAttribute("default")
defer = BooleanAttribute("defer")
dir = SimpleAttribute("dir")
dirname = SimpleAttribute("dirname")
disabled = BooleanAttribute("disabled")
download = SimpleAttribute("download")
draggable = BooleanAttribute("draggable")
enctype = SimpleAttribute("enctype")
enterkeyhint = SimpleAttribute("enterkeyhint")
elementtiming = SimpleAttribute("elementtiming")
fetchpriority = SimpleAttribute("fetchpriority")
for_ = SimpleAttribute("for")
form = SimpleAttribute("form")
formaction = SimpleAttribute("formaction")
formenctype = SimpleAttribute("formenctype")
formmethod = SimpleAttribute("formmethod")
formnovalidate = BooleanAttribute("formnovalidate")
formtarget = SimpleAttribute("formtarget")
headers = SimpleAttribute("headers")
height = SimpleAttribute("height")
hidden = BooleanAttribute("hidden")
high = SimpleAttribute("high")
href = SimpleAttribute("href")
hreflang = SimpleAttribute("hreflang")
http_equiv = SimpleAttribute("http-equiv")
integrity = SimpleAttribute("integrity")
inputmode = SimpleAttribute("inputmode")
ismap = BooleanAttribute("ismap")
itemprop = SimpleAttribute("itemprop")
kind = SimpleAttribute("kind")
label = SimpleAttribute("label")
lang = SimpleAttribute("lang")
language = SimpleAttribute("language")
loading = SimpleAttribute("loading")
list_ = SimpleAttribute("list")
loop = BooleanAttribute("loop")
low = SimpleAttribute("low")
max = SimpleAttribute("max")
maxlength = SimpleAttribute("maxlength")
minlength = SimpleAttribute("minlength")
media = SimpleAttribute("media")
method = SimpleAttribute("method")
min = SimpleAttribute("min")
multiple = BooleanAttribute("multiple")
muted = BooleanAttribute("muted")
name = SimpleAttribute("name")
novalidate = BooleanAttribute("novalidate")
open = BooleanAttribute("open")
optimum = SimpleAttribute("optimum")
pattern = SimpleAttribute("pattern")
ping = ComposedAttribute("ping", compose_policy=whitespace_composer)
placeholder = SimpleAttribute("placeholder")
playsinline = BooleanAttribute("playsinline")
poster = SimpleAttribute("poster")
preload = SimpleAttribute("preload")
readonly = BooleanAttribute("readonly")
referrerpolicy = SimpleAttribute("referrerpolicy")
rel = ComposedAttribute("rel", compose_policy=whitespace_composer)
required = BooleanAttribute("required")
reversed = BooleanAttribute("reversed")
role = SimpleAttribute("role")
rows = SimpleAttribute("rows")
rowspan = SimpleAttribute("rowspan")
sandbox = ComposedAttribute("sandbox", compose_policy=whitespace_composer)
scope = SimpleAttribute("scope")
selected = BooleanAttribute("selected")
shape = SimpleAttribute("shape")
size = SimpleAttribute("size")
slot = SimpleAttribute("slot")
span = SimpleAttribute("span")
spellcheck = BooleanAttribute("spellcheck")
src = SimpleAttribute("src")
srcdoc = SimpleAttribute("srcdoc")
srclang = SimpleAttribute("srclang")
srcset = SimpleAttribute("srcset")
start = SimpleAttribute("start")
step = SimpleAttribute("step")
summary = SimpleAttribute("summary")
tabindex = SimpleAttribute("tabindex")
target = SimpleAttribute("target")
title = SimpleAttribute("title")
translate = BooleanAttribute("translate")
type_ = SimpleAttribute("type")
usemap = SimpleAttribute("usemap")
value = SimpleAttribute("value")
width = SimpleAttribute("width")
wrap = SimpleAttribute("wrap")
